mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.demo.kfjira.entity

spring:
  jpa:
    show-sql: true
  dataSource:
    username: zhanghui@onex
    password: Sjtu403c
    url: jdbc:mysql://onex.mysql.database.chinacloudapi.cn:3306/lacoste?useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: ""
    pool:
      max-active: 32
      max-wait: -1
      max-idle: 8
      min-idle: 0

logging:
  level:
    com.cs.cstools.mapper: debug

